export const theme = {
  colors: {
    bg: '#f8f8f7',
    surface: '#ffffff',
    surface2: '#f1f0ee',
    border: '#e5e2df',
    primary: '#550b14',
    primaryHover: '#440910',
    primaryLight: '#7e1a27',
    accent: '#7e6961',
    accentHover: '#6a5750',
    accentLight: '#9a8a84',
    text: '#1a1412',
    textSecondary: '#5c524d',
    muted: '#8a7f7a',
    success: '#2d6a4f',
    warning: '#b8860b',
    error: '#c1121f',
    gold: '#c9a96e',
    goldLight: '#e8d5a3',
    rose: '#e8b4b8',
    roseLight: '#f5d6d9',
    cream: '#faf6f1',
  },
  fonts: {
    display: "'Cormorant Garamond', serif",
    body: "'DM Sans', sans-serif",
  },
  fontWeights: {
    display: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    body: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
  },
  fontSize: {
    h1: 'clamp(2.5rem, 5vw, 4.5rem)',
    h2: 'clamp(2rem, 4vw, 3.5rem)',
    h3: 'clamp(1.5rem, 3vw, 2rem)',
    h4: 'clamp(1.25rem, 2vw, 1.5rem)',
    body: 'clamp(0.938rem, 1.2vw, 1.063rem)',
    small: '0.875rem',
    xs: '0.75rem',
  },
  spacing: {
    section: {
      sm: 'py-12 sm:py-16 lg:py-20',
      md: 'py-16 sm:py-20 lg:py-24',
      lg: 'py-20 sm:py-24 lg:py-32',
    },
    container: {
      default: 'mx-auto max-w-7xl px-4 sm:px-6 lg:px-8',
      narrow: 'mx-auto max-w-4xl px-4 sm:px-6 lg:px-8',
    },
  },
  borderRadius: {
    sm: '0.375rem',
    md: '0.5rem',
    lg: '0.75rem',
    xl: '1rem',
    '2xl': '1.5rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px rgba(26, 20, 18, 0.05)',
    md: '0 4px 6px -1px rgba(26, 20, 18, 0.08), 0 2px 4px -2px rgba(26, 20, 18, 0.05)',
    lg: '0 10px 15px -3px rgba(26, 20, 18, 0.08), 0 4px 6px -4px rgba(26, 20, 18, 0.05)',
    xl: '0 20px 25px -5px rgba(26, 20, 18, 0.1), 0 8px 10px -6px rgba(26, 20, 18, 0.05)',
  },
  animations: {
    duration: {
      fast: '150ms',
      normal: '200ms',
      slow: '300ms',
      slower: '500ms',
    },
    easing: {
      default: 'cubic-bezier(0.4, 0, 0.2, 1)',
      in: 'cubic-bezier(0.4, 0, 1, 1)',
      out: 'cubic-bezier(0, 0, 0.2, 1)',
      inOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
  },
  services: [
    {
      id: 'manucure-classique',
      name: 'Manucure Classique',
      description: 'Soin complet des mains avec limage, repousse des cuticules et vernis classique.',
      duration: 45,
      price: 35,
      category: 'manucure',
    },
    {
      id: 'manucure-gel',
      name: 'Manucure Gel',
      description: 'Pose de vernis semi-permanent pour une tenue parfaite jusqu\'à 3 semaines.',
      duration: 60,
      price: 55,
      category: 'manucure',
    },
    {
      id: 'nail-art-simple',
      name: 'Nail Art Simple',
      description: 'Design personnalisé simple : points, lignes, motifs géométriques.',
      duration: 30,
      price: 15,
      category: 'nail-art',
    },
    {
      id: 'nail-art-avance',
      name: 'Nail Art Avancé',
      description: 'Création artistique complexe : marbrure, dégradé, fleurs, motifs détaillés.',
      duration: 60,
      price: 35,
      category: 'nail-art',
    },
    {
      id: 'french-manucure',
      name: 'French Manucure',
      description: 'Le grand classique revisité : french traditionnelle ou colorée.',
      duration: 50,
      price: 45,
      category: 'manucure',
    },
    {
      id: 'soin-complet',
      name: 'Soin Complet des Mains',
      description: 'Soin spa des mains avec gommage, masque hydratant et massage.',
      duration: 75,
      price: 65,
      category: 'soin',
    },
    {
      id: 'pose-ongles',
      name: 'Pose d\'Ongles (Chablon/Capsule)',
      description: 'Extension d\'ongles par chablon ou capsule pour une longueur personnalisée.',
      duration: 90,
      price: 75,
      category: 'extension',
    },
    {
      id: 'remplissage',
      name: 'Remplissage',
      description: 'Remplissage pour ongles gel ou résine avec soin des cuticules.',
      duration: 60,
      price: 50,
      category: 'entretien',
    },
    {
      id: 'depose',
      name: 'Dépose d\'Ongles',
      description: 'Dépose professionnelle sans abîmer l\'ongle naturel.',
      duration: 30,
      price: 20,
      category: 'entretien',
    },
    {
      id: 'pedicure-classique',
      name: 'Pédicure Classique',
      description: 'Soin des pieds complet avec limage, cuticules et vernis.',
      duration: 50,
      price: 40,
      category: 'pedicure',
    },
    {
      id: 'pedicure-gel',
      name: 'Pédicure Gel',
      description: 'Pose de vernis semi-permanent pour les pieds, tenue longue durée.',
      duration: 65,
      price: 55,
      category: 'pedicure',
    },
    {
      id: 'nail-art-pieds',
      name: 'Nail Art Pieds',
      description: 'Design personnalisé pour les ongles de pieds.',
      duration: 30,
      price: 20,
      category: 'nail-art',
    },
  ],
  categories: [
    { id: 'manucure', name: 'Manucure', icon: 'Hand' },
    { id: 'nail-art', name: 'Nail Art', icon: 'Palette' },
    { id: 'soin', name: 'Soins', icon: 'Sparkles' },
    { id: 'extension', name: 'Extensions', icon: 'Ruler' },
    { id: 'entretien', name: 'Entretien', icon: 'RefreshCw' },
    { id: 'pedicure', name: 'Pédicure', icon: 'Foot' },
  ],
  businessHours: {
    monday: { open: '09:00', close: '18:00' },
    tuesday: { open: '09:00', close: '18:00' },
    wednesday: { open: '09:00', close: '18:00' },
    thursday: { open: '09:00', close: '19:00' },
    friday: { open: '09:00', close: '19:00' },
    saturday: { open: '10:00', close: '17:00' },
    sunday: null,
  },
  contact: {
    phone: '+33 6 12 34 56 78',
    email: 'contact@ixshel-co.fr',
    address: '12 Rue des Artisans, 75012 Paris',
    instagram: '@ixshel_co',
    whatsapp: '+33612345678',
  },
} as const;

export type Service = typeof theme.services[0];
export type ServiceCategory = typeof theme.categories[0];
export type BusinessHours = typeof theme.businessHours;